export type BandId = "beach" | "canal" | "park" | "street";

export type House = {
  lot: number;
  name: string;
  size: string;
  beds: string;
  area: string;
  style: string;
  cladding: string;
  image: string;
  furnished: number;
  blurb: string;
};

export type Band = {
  id: BandId;
  title: string;
  kicker: string;
  note: string;
  row: string;
  water: string;
  price: string;
  houses: House[];
};

const kit = "Same Caribbean Salt furniture kit as the villas — linen, rattan, teak, factory-fitted wet pack.";

export const BANDS: Band[] = [
  {
    id: "beach",
    title: "Beach row",
    kicker: "Lots 196 · 197 · 198 · 199 · Chetumal Bay",
    note: "The four big plans, 20 × 40 ft, on the bay. Mixed roofs and cladding so the beach is not a clone row. Decks face the water. Quarter-acre lots.",
    row: "/cottage/nb-beach.jpg",
    water: "Open bay",
    price: "$340k – $420k furnished",
    houses: [
      {
        lot: 196,
        name: "Bay hip",
        size: "20 × 40 ft",
        beds: "3 bed / 2 bath",
        area: "800 sf + screened porch",
        style: "Hip roof, screened porch",
        cladding: "Salt-white siding, white rail",
        image: "/cottage/nb-196.jpg",
        furnished: 412000,
        blurb: `The family beach house. Three bedrooms, a screened porch, terrace on the sand. ${kit}`,
      },
      {
        lot: 197,
        name: "Sea-glass pool",
        size: "20 × 40 ft",
        beds: "2 bed / 2.5 bath",
        area: "800 sf + side verandas",
        style: "Gable, plunge pool",
        cladding: "Sea-glass aqua, white trim",
        image: "/cottage/nb-197.jpg",
        furnished: 398000,
        blurb: `Two bedrooms, two-and-a-half baths, a small pool on the bay side. ${kit}`,
      },
      {
        lot: 198,
        name: "Charcoal terrace",
        size: "20 × 40 ft",
        beds: "3 bed / 2 bath",
        area: "800 sf + deep terrace",
        style: "Hip roof, metal",
        cladding: "Charcoal metal, white trim",
        image: "/cottage/nb-198.jpg",
        furnished: 420000,
        blurb: `Three bedrooms and a deep teak terrace on the sand. The evening room is outside. ${kit}`,
      },
      {
        lot: 199,
        name: "Teak L-bay",
        size: "20 × 40 ft L",
        beds: "3 bed / 2 bath",
        area: "800 sf + wrap deck",
        style: "Joined L, gable",
        cladding: "Oiled teak hardwood",
        image: "/cottage/nb-199.jpg",
        furnished: 418000,
        blurb: `An L-plan on the last bay lot. Wrap deck, three bedrooms, more privacy from the road. ${kit}`,
      },
    ],
  },
  {
    id: "canal",
    title: "Canal middle",
    kicker: "Lots 103 · 104 · 105 · 106 · 107 · inland canal",
    note: "Middle 20 × 30 ft plans on the far canal. Mixed metal, hardwood, and paint. Level land, then a 5 ft drop to the water. Teak steps on a couple of lots for a kayak put-in.",
    row: "/cottage/nb-canal.jpg",
    water: "Inland canal · 5 ft drop",
    price: "$260k – $310k furnished",
    houses: [
      {
        lot: 103,
        name: "Canal lodge",
        size: "20 × 30 ft",
        beds: "2 bed / 1 bath",
        area: "600 sf + canal deck",
        style: "Gable, hardwood",
        cladding: "Oiled teak",
        image: "/cottage/nb-103.jpg",
        furnished: 292000,
        blurb: `Dark wood on the canal bank. Two bedrooms, steps down to a kayak landing. ${kit}`,
      },
      {
        lot: 104,
        name: "Blue porch",
        size: "20 × 30 ft",
        beds: "3 bed / 1 bath",
        area: "600 sf + porch",
        style: "Vertical metal, porch",
        cladding: "Sky-blue metal, white rail",
        image: "/cottage/nb-104.jpg",
        furnished: 304000,
        blurb: `Three compact bedrooms, a white porch facing the canal. ${kit}`,
      },
      {
        lot: 105,
        name: "White hip canal",
        size: "20 × 30 ft",
        beds: "2 bed / 2 bath",
        area: "600 sf + deck",
        style: "Hip roof",
        cladding: "Salt-white siding",
        image: "/cottage/nb-105.jpg",
        furnished: 288000,
        blurb: `Two bedrooms, two baths, white hip roof on the bank. ${kit}`,
      },
      {
        lot: 106,
        name: "Pine gable",
        size: "20 × 30 ft",
        beds: "2 bed / 1 bath",
        area: "600 sf + porch",
        style: "Gable, metal",
        cladding: "Pine-gold metal",
        image: "/cottage/nb-106.jpg",
        furnished: 274000,
        blurb: `Warm metal siding, two bedrooms, a small porch at the 5 ft drop. ${kit}`,
      },
      {
        lot: 107,
        name: "Sage canal",
        size: "20 × 30 ft",
        beds: "3 bed / 1 bath",
        area: "600 sf + deck",
        style: "Hip, painted",
        cladding: "Sea-glass sage",
        image: "/cottage/nb-107.jpg",
        furnished: 298000,
        blurb: `Three bedrooms in a 20 × 30, sage siding, canal deck. ${kit}`,
      },
    ],
  },
  {
    id: "park",
    title: "Park street",
    kicker: "Lots 234 · 235 · 236 · 237 · 238 · 239 · near Park #3",
    note: "Medium 20 × 34 ft plans on the interior street by the park. Not waterfront. Mixed gable, hip, hardwood, and metal so the block is not cloned.",
    row: "/cottage/nb-park.jpg",
    water: "Interior · park side",
    price: "$270k – $320k furnished",
    houses: [
      {
        lot: 234,
        name: "Park gable",
        size: "20 × 34 ft",
        beds: "2 bed / 2 bath",
        area: "680 sf + porch",
        style: "Gable, porch",
        cladding: "Salt-white",
        image: "/cottage/nb-234.jpg",
        furnished: 312000,
        blurb: `White gable facing the park street. Two bedrooms, two baths. ${kit}`,
      },
      {
        lot: 235,
        name: "Hardwood park",
        size: "20 × 34 ft",
        beds: "2 bed / 1 bath",
        area: "680 sf",
        style: "Gable, stained wood",
        cladding: "Oiled hardwood",
        image: "/cottage/nb-235.jpg",
        furnished: 304000,
        blurb: `Stained wood on the park block. Two bedrooms. ${kit}`,
      },
      {
        lot: 236,
        name: "Charcoal park",
        size: "20 × 34 ft",
        beds: "2 bed / 2 bath",
        area: "680 sf + porch",
        style: "Hip, metal",
        cladding: "Charcoal metal, white trim",
        image: "/cottage/nb-236.jpg",
        furnished: 318000,
        blurb: `Metal hip roof, two baths, a small porch to the street. ${kit}`,
      },
      {
        lot: 237,
        name: "Aqua park",
        size: "20 × 34 ft",
        beds: "2 bed / 1 bath",
        area: "680 sf + porch",
        style: "Gable, painted",
        cladding: "Sea-glass aqua",
        image: "/cottage/nb-237.jpg",
        furnished: 286000,
        blurb: `Aqua siding, white porch, two bedrooms. ${kit}`,
      },
      {
        lot: 238,
        name: "Teak park",
        size: "20 × 34 ft",
        beds: "2 bed / 2 bath",
        area: "680 sf + wrap",
        style: "L-gable, hardwood",
        cladding: "Oiled teak",
        image: "/cottage/nb-238.jpg",
        furnished: 320000,
        blurb: `Teak L on the park street. More privacy from the road. ${kit}`,
      },
      {
        lot: 239,
        name: "Blue park porch",
        size: "20 × 34 ft",
        beds: "2 bed / 1 bath",
        area: "680 sf + porch",
        style: "Vertical metal",
        cladding: "Sky-blue metal",
        image: "/cottage/nb-239.jpg",
        furnished: 278000,
        blurb: `Blue metal, white rail, two bedrooms at the end of the block. ${kit}`,
      },
    ],
  },
  {
    id: "street",
    title: "Small street",
    kicker: "Lots 241 · 252 – 259 · interior street",
    note: "The small plans — 16 × 24, 16 × 20, 16 × 16, a loft cabin. Street view, not the water. Mixed so nine lots do not read as one model.",
    row: "/cottage/nb-street.jpg",
    water: "Interior street",
    price: "$155k – $210k furnished",
    houses: [
      {
        lot: 241,
        name: "Aqua studio",
        size: "16 × 16 ft",
        beds: "Studio / 1 bath",
        area: "256 sf + stoop",
        style: "Cube, hip",
        cladding: "Sea-glass aqua",
        image: "/cottage/nb-241.jpg",
        furnished: 158000,
        blurb: `The smallest cube on the street. One room, one bath. ${kit}`,
      },
      {
        lot: 252,
        name: "White two-bed",
        size: "16 × 24 ft",
        beds: "2 bed / 1 bath",
        area: "384 sf + porch",
        style: "Gable, porch",
        cladding: "Salt-white",
        image: "/cottage/nb-252.jpg",
        furnished: 198000,
        blurb: `Two small bedrooms, a porch to the street. Strong nightly. ${kit}`,
      },
      {
        lot: 253,
        name: "Teak one-bed",
        size: "16 × 24 ft",
        beds: "1 bed / 1 bath",
        area: "384 sf",
        style: "Gable, hardwood",
        cladding: "Oiled teak",
        image: "/cottage/nb-253.jpg",
        furnished: 186000,
        blurb: `One bedroom in dark wood. Quiet annual. ${kit}`,
      },
      {
        lot: 254,
        name: "Charcoal one-bed",
        size: "16 × 20 ft",
        beds: "1 bed / 1 bath",
        area: "320 sf + stoop",
        style: "Shed / hip metal",
        cladding: "Charcoal metal",
        image: "/cottage/nb-254.jpg",
        furnished: 172000,
        blurb: `Compact metal one-bed. ${kit}`,
      },
      {
        lot: 255,
        name: "Aqua porch",
        size: "16 × 24 ft",
        beds: "2 bed / 1 bath",
        area: "384 sf + porch",
        style: "Gable, painted",
        cladding: "Sea-glass aqua",
        image: "/cottage/nb-255.jpg",
        furnished: 194000,
        blurb: `Aqua two-bed with a white porch. ${kit}`,
      },
      {
        lot: 256,
        name: "Loft cabin",
        size: "14 × 16 ft",
        beds: "Loft / 1 bath",
        area: "224 sf + roof deck",
        style: "Tiny loft",
        cladding: "Dark metal and teak",
        image: "/cottage/nb-256.jpg",
        furnished: 164000,
        blurb: `A loft cabin with a roof deck. One person, or a lock-off. ${kit}`,
      },
      {
        lot: 257,
        name: "Pine studio",
        size: "16 × 20 ft",
        beds: "Studio / 1 bath",
        area: "320 sf",
        style: "Gable, metal",
        cladding: "Pine-gold metal",
        image: "/cottage/nb-257.jpg",
        furnished: 168000,
        blurb: `Warm metal studio on the street. ${kit}`,
      },
      {
        lot: 258,
        name: "White square",
        size: "20 × 20 ft",
        beds: "1 bed / 1 bath",
        area: "400 sf + porch",
        style: "Gable",
        cladding: "Salt-white",
        image: "/cottage/nb-258.jpg",
        furnished: 208000,
        blurb: `A 20 × 20 one-bed. The largest of the small street. ${kit}`,
      },
      {
        lot: 259,
        name: "Blue two-bed",
        size: "16 × 24 ft",
        beds: "2 bed / 1 bath",
        area: "384 sf + porch",
        style: "Vertical metal",
        cladding: "Sky-blue metal",
        image: "/cottage/nb-259.jpg",
        furnished: 188000,
        blurb: `Blue metal two-bed at the end of the street. ${kit}`,
      },
    ],
  },
];

export function bandById(id: BandId) {
  return BANDS.find((b) => b.id === id) ?? BANDS[0];
}

export function houseOn(band: Band, lot: number) {
  return band.houses.find((h) => h.lot === lot) ?? band.houses[0];
}
