/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R3dRouteImport } from './routes/3d'
import { Route as MapRouteImport } from './routes/map'
import { Route as Moonlightbay3dviewRouteImport } from './routes/moonlightbay3dview'
import { Route as WalkRouteImport } from './routes/walk'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R3dRoute = R3dRouteImport.update({
  id: '/3d',
  path: '/3d',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const Moonlightbay3dviewRoute = Moonlightbay3dviewRouteImport.update({
  id: '/moonlightbay3dview',
  path: '/moonlightbay3dview',
  getParentRoute: () => rootRouteImport,
} as any)
const WalkRoute = WalkRouteImport.update({
  id: '/walk',
  path: '/walk',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/3d': typeof R3dRoute
  '/map': typeof MapRoute
  '/moonlightbay3dview': typeof Moonlightbay3dviewRoute
  '/walk': typeof WalkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/3d': typeof R3dRoute
  '/map': typeof MapRoute
  '/moonlightbay3dview': typeof Moonlightbay3dviewRoute
  '/walk': typeof WalkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/3d': typeof R3dRoute
  '/map': typeof MapRoute
  '/moonlightbay3dview': typeof Moonlightbay3dviewRoute
  '/walk': typeof WalkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/3d' | '/map' | '/moonlightbay3dview' | '/walk'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/3d' | '/map' | '/moonlightbay3dview' | '/walk'
  id: '__root__' | '/' | '/3d' | '/map' | '/moonlightbay3dview' | '/walk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R3dRoute: typeof R3dRoute
  MapRoute: typeof MapRoute
  Moonlightbay3dviewRoute: typeof Moonlightbay3dviewRoute
  WalkRoute: typeof WalkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/3d': {
      id: '/3d'
      path: '/3d'
      fullPath: '/3d'
      preLoaderRoute: typeof R3dRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moonlightbay3dview': {
      id: '/moonlightbay3dview'
      path: '/moonlightbay3dview'
      fullPath: '/moonlightbay3dview'
      preLoaderRoute: typeof Moonlightbay3dviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walk': {
      id: '/walk'
      path: '/walk'
      fullPath: '/walk'
      preLoaderRoute: typeof WalkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R3dRoute: R3dRoute,
  MapRoute: MapRoute,
  Moonlightbay3dviewRoute: Moonlightbay3dviewRoute,
  WalkRoute: WalkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
